# Generated by Django 5.2.4 on 2025-07-31 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_alter_comment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='trophy_icons/')),
                ('subraddot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='social_app.subraddot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
