# Generated by Django 5.2.4 on 2025-07-29 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_alter_subreddit_creator_alter_votepost_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subreddit',
            new_name='Subraddot',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subreddit',
            new_name='subraddot',
        ),
    ]
