# Generated by Django 5.2.4 on 2025-07-29 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_rename_subreddit_subraddot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subraddot',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/subraddot/banners/'),
        ),
        migrations.AlterField(
            model_name='subraddot',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subraddots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subraddot',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/subraddot/icons/'),
        ),
    ]
