# Generated by Django 5.2.4 on 2025-07-31 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_trophy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='subraddot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='social_app.subraddot'),
        ),
    ]
