# Generated by Django 5.2.4 on 2025-07-29 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_alter_subraddot_banner_alter_subraddot_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subraddot',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_subraddots', to=settings.AUTH_USER_MODEL),
        ),
    ]
