# Generated by Django 5.2.4 on 2025-07-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_alter_trophy_subraddot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
